# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7a50f2945ff790df8341d45bd03b12d667738dac86b00cb286477800e365a4eb6a0e797cd29622879d97252f4275a0edabead7cd272f8aa7d3c2ddfc84335db

test:
  secret_key_base: c9f3f76ee4dbc1bde51c6ab466bfcaafb28b44044b92060e3848cac968dd010a09f8c36e7bc5202aa5cdc7be48464cae052a4c951dc1947738ec46ad650611ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
